org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Wersje - sprawdz aktualne na https://fabricmc.net/develop/ (dla Minecraft 26.3 zmien minecraft_version i fabric_api_version)
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.15-SNAPSHOT
fabric_api_version=0.160.0+26.2

mod_version=1.0.0
maven_group=com.pingroom
archives_base_name=pingroom
